"""phase3_tables

Revision ID: 96cb1f518f0f
Revises: 003
Create Date: 2026-04-14 15:12:09.972741
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '96cb1f518f0f'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shadow_signal_diffs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=80), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('primary_provider', sa.String(length=100), nullable=False),
    sa.Column('shadow_provider', sa.String(length=100), nullable=False),
    sa.Column('compared_at', sa.DateTime(), nullable=False),
    sa.Column('max_delta', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('metric_deltas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('threshold_crossed', sa.Boolean(), nullable=False),
    sa.Column('alert_triggered', sa.Boolean(), nullable=False),
    sa.Column('threshold_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shadow_diff_city_time', 'shadow_signal_diffs', ['city', 'compared_at'], unique=False)
    op.create_index('idx_shadow_diff_zone_type_time', 'shadow_signal_diffs', ['zone', 'signal_type', 'compared_at'], unique=False)
    op.create_index(op.f('ix_shadow_signal_diffs_city'), 'shadow_signal_diffs', ['city'], unique=False)
    op.create_index(op.f('ix_shadow_signal_diffs_compared_at'), 'shadow_signal_diffs', ['compared_at'], unique=False)
    op.create_index(op.f('ix_shadow_signal_diffs_signal_type'), 'shadow_signal_diffs', ['signal_type'], unique=False)
    op.create_index(op.f('ix_shadow_signal_diffs_zone'), 'shadow_signal_diffs', ['zone'], unique=False)
    op.create_table('signal_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=80), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('normalized_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('quality_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signal_snapshot_city_time', 'signal_snapshots', ['city', 'captured_at'], unique=False)
    op.create_index('idx_signal_snapshot_zone_type_time', 'signal_snapshots', ['zone', 'signal_type', 'captured_at'], unique=False)
    op.create_index(op.f('ix_signal_snapshots_captured_at'), 'signal_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_signal_snapshots_city'), 'signal_snapshots', ['city'], unique=False)
    op.create_index(op.f('ix_signal_snapshots_signal_type'), 'signal_snapshots', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signal_snapshots_zone'), 'signal_snapshots', ['zone'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_worker_unread', 'notifications', ['worker_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_worker_id'), 'notifications', ['worker_id'], unique=False)
    op.create_table('decision_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('lifecycle_stage', sa.String(length=50), nullable=False),
    sa.Column('decision_source', sa.String(length=50), nullable=False),
    sa.Column('system_decision', sa.String(length=20), nullable=True),
    sa.Column('resulting_status', sa.String(length=20), nullable=False),
    sa.Column('final_label', sa.String(length=20), nullable=True),
    sa.Column('label_source', sa.String(length=50), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('payout_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('review_wait_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fraud_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('trust_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('decision_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision_policy_version', sa.String(length=50), nullable=False),
    sa.Column('signal_snapshot_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_decision_log_claim_stage_time', 'decision_logs', ['claim_id', 'lifecycle_stage', 'created_at'], unique=False)
    op.create_index('idx_decision_log_worker_time', 'decision_logs', ['worker_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_decision_logs_claim_id'), 'decision_logs', ['claim_id'], unique=False)
    op.create_index(op.f('ix_decision_logs_created_at'), 'decision_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_decision_logs_decision_source'), 'decision_logs', ['decision_source'], unique=False)
    op.create_index(op.f('ix_decision_logs_event_id'), 'decision_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_decision_logs_final_label'), 'decision_logs', ['final_label'], unique=False)
    op.create_index(op.f('ix_decision_logs_lifecycle_stage'), 'decision_logs', ['lifecycle_stage'], unique=False)
    op.create_index(op.f('ix_decision_logs_policy_id'), 'decision_logs', ['policy_id'], unique=False)
    op.create_index(op.f('ix_decision_logs_resulting_status'), 'decision_logs', ['resulting_status'], unique=False)
    op.create_index(op.f('ix_decision_logs_system_decision'), 'decision_logs', ['system_decision'], unique=False)
    op.create_index(op.f('ix_decision_logs_worker_id'), 'decision_logs', ['worker_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.drop_constraint('cities_slug_key', 'cities', type_='unique')
    op.drop_index('ix_cities_slug', table_name='cities')
    op.create_index(op.f('ix_cities_slug'), 'cities', ['slug'], unique=True)
    op.drop_index('ix_events_type', table_name='events')
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_foreign_key(None, 'events', 'zones', ['zone_id'], ['id'])
    op.add_column('fraud_logs', sa.Column('is_simulated', sa.Boolean(), nullable=True))
    op.add_column('fraud_logs', sa.Column('simulation_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_fraud_logs_is_simulated'), 'fraud_logs', ['is_simulated'], unique=False)
    op.add_column('worker_activity', sa.Column('is_simulated', sa.Boolean(), nullable=True))
    op.add_column('worker_activity', sa.Column('simulation_type', sa.String(length=50), nullable=True))
    op.create_index('idx_activity_simulated', 'worker_activity', ['is_simulated'], unique=False)
    op.create_index(op.f('ix_worker_activity_is_simulated'), 'worker_activity', ['is_simulated'], unique=False)
    op.create_index(op.f('ix_worker_activity_worker_id'), 'worker_activity', ['worker_id'], unique=False)
    op.create_index(op.f('ix_worker_activity_zone'), 'worker_activity', ['zone'], unique=False)
    op.create_foreign_key(None, 'worker_activity', 'zones', ['zone_id'], ['id'])
    op.drop_constraint('workers_phone_key', 'workers', type_='unique')
    op.drop_index('ix_workers_phone', table_name='workers')
    op.create_index(op.f('ix_workers_phone'), 'workers', ['phone'], unique=True)
    op.create_foreign_key(None, 'workers', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'workers', 'zones', ['zone_id'], ['id'])
    op.drop_constraint('zone_risk_profiles_zone_id_key', 'zone_risk_profiles', type_='unique')
    op.create_index(op.f('ix_zone_risk_profiles_zone_id'), 'zone_risk_profiles', ['zone_id'], unique=True)
    op.drop_constraint('zone_threshold_profiles_zone_id_key', 'zone_threshold_profiles', type_='unique')
    op.create_index(op.f('ix_zone_threshold_profiles_zone_id'), 'zone_threshold_profiles', ['zone_id'], unique=True)
    op.drop_constraint('zones_slug_key', 'zones', type_='unique')
    op.drop_index('ix_zones_slug', table_name='zones')
    op.create_index(op.f('ix_zones_slug'), 'zones', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zones_slug'), table_name='zones')
    op.create_index('ix_zones_slug', 'zones', ['slug'], unique=False)
    op.create_unique_constraint('zones_slug_key', 'zones', ['slug'])
    op.drop_index(op.f('ix_zone_threshold_profiles_zone_id'), table_name='zone_threshold_profiles')
    op.create_unique_constraint('zone_threshold_profiles_zone_id_key', 'zone_threshold_profiles', ['zone_id'])
    op.drop_index(op.f('ix_zone_risk_profiles_zone_id'), table_name='zone_risk_profiles')
    op.create_unique_constraint('zone_risk_profiles_zone_id_key', 'zone_risk_profiles', ['zone_id'])
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_index(op.f('ix_workers_phone'), table_name='workers')
    op.create_index('ix_workers_phone', 'workers', ['phone'], unique=False)
    op.create_unique_constraint('workers_phone_key', 'workers', ['phone'])
    op.drop_constraint(None, 'worker_activity', type_='foreignkey')
    op.drop_index(op.f('ix_worker_activity_zone'), table_name='worker_activity')
    op.drop_index(op.f('ix_worker_activity_worker_id'), table_name='worker_activity')
    op.drop_index(op.f('ix_worker_activity_is_simulated'), table_name='worker_activity')
    op.drop_index('idx_activity_simulated', table_name='worker_activity')
    op.drop_column('worker_activity', 'simulation_type')
    op.drop_column('worker_activity', 'is_simulated')
    op.drop_index(op.f('ix_fraud_logs_is_simulated'), table_name='fraud_logs')
    op.drop_column('fraud_logs', 'simulation_type')
    op.drop_column('fraud_logs', 'is_simulated')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.create_index('ix_events_type', 'events', ['event_type'], unique=False)
    op.drop_index(op.f('ix_cities_slug'), table_name='cities')
    op.create_index('ix_cities_slug', 'cities', ['slug'], unique=False)
    op.create_unique_constraint('cities_slug_key', 'cities', ['slug'])
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_decision_logs_worker_id'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_system_decision'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_resulting_status'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_policy_id'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_lifecycle_stage'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_final_label'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_event_id'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_decision_source'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_created_at'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_claim_id'), table_name='decision_logs')
    op.drop_index('idx_decision_log_worker_time', table_name='decision_logs')
    op.drop_index('idx_decision_log_claim_stage_time', table_name='decision_logs')
    op.drop_table('decision_logs')
    op.drop_index(op.f('ix_notifications_worker_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_index('idx_notifications_worker_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_signal_snapshots_zone'), table_name='signal_snapshots')
    op.drop_index(op.f('ix_signal_snapshots_signal_type'), table_name='signal_snapshots')
    op.drop_index(op.f('ix_signal_snapshots_city'), table_name='signal_snapshots')
    op.drop_index(op.f('ix_signal_snapshots_captured_at'), table_name='signal_snapshots')
    op.drop_index('idx_signal_snapshot_zone_type_time', table_name='signal_snapshots')
    op.drop_index('idx_signal_snapshot_city_time', table_name='signal_snapshots')
    op.drop_table('signal_snapshots')
    op.drop_index(op.f('ix_shadow_signal_diffs_zone'), table_name='shadow_signal_diffs')
    op.drop_index(op.f('ix_shadow_signal_diffs_signal_type'), table_name='shadow_signal_diffs')
    op.drop_index(op.f('ix_shadow_signal_diffs_compared_at'), table_name='shadow_signal_diffs')
    op.drop_index(op.f('ix_shadow_signal_diffs_city'), table_name='shadow_signal_diffs')
    op.drop_index('idx_shadow_diff_zone_type_time', table_name='shadow_signal_diffs')
    op.drop_index('idx_shadow_diff_city_time', table_name='shadow_signal_diffs')
    op.drop_table('shadow_signal_diffs')
    # ### end Alembic commands ###
